services:
  postgres:
    image: postgres:15
    container_name: hc_postgres_new
    restart: always
    environment:
      POSTGRES_USER: hc_user
      POSTGRES_PASSWORD: hc_password
      POSTGRES_DB: hc_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hc_frontend_new
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_URL=http://gateway:8080
    depends_on:
      - gateway
    networks:
      - app-network

  gateway:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./gateway-service/.env
    depends_on:
      - postgres
    networks:
      - app-network

  dsdgen:
    build:
      context: ./dsdgen-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    env_file:
      - ./dsdgen-service/.env
    environment:
      - N8N_WEBHOOK_URL=http://n8n:5678/webhook/slack-notification
    depends_on:
      - postgres
      - n8n
    networks:
      - app-network

  dsdcheck:
    build:
      context: ./dsdcheck-service
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    volumes:
      - ./dsdcheck-service/app/resources:/app/app/resources
    env_file:
      - ./dsdcheck-service/.env
    depends_on:
      - postgres
    networks:
      - app-network

  n8n:
    build:
      context: ./n8n-service
      dockerfile: Dockerfile
    container_name: hc_n8n
    ports:
      - "5678:5678"
    env_file:
      - ./n8n-service/.env
    volumes:
      - n8n_data:/home/node/.n8n
      - n8n_workflows:/data/workflows
      - ./n8n-service/workflows:/data/workflows/init
    networks:
      - app-network

volumes:
  pgdata:
  n8n_data:
  n8n_workflows:

networks:
  app-network:
    driver: bridge
