apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
  labels:
    app: n8n
type: Opaque
data:
  # 실제 사용 시 Slack Webhook URL을 base64로 인코딩하여 입력
  # echo -n "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK" | base64
  slack_webhook: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDA4TkE1VTdQRFkvQjA4VjRHU0tWTUwvY2NPVngxQndlQnlYWVlldnduY0E2Y0tx 