name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~
            if [ ! -d "aws_develope" ]; then
              git clone https://github.com/junyeongccom/aws_develope.git
            fi
            cd aws_develope
            git pull origin main

            sudo yum update -y
            sudo yum install -y docker git
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker ec2-user

            sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

            for dir in chatbot-service dsdcheck_service dsdgen_service esgdsd_service frontend gateway_service irsummary_service stocktrend_service
            do
              if [ ! -f "$dir/.env" ]; then
                touch "$dir/.env"
              fi
            done

            sudo docker-compose down || true
            sudo docker-compose up -d --build
